### ISSUE TITLE
Does not Build on ghc 7.10, several issues

### ISSUE THREAD

**Issue by dasimmet** [clckwrks/clckwrks#2]
Hi, I was trying to build example-dot-org in ghc 7.10 (arch linux) using cabal, but some dependencies didnt compile:
- web-plugins: in Web/Plugins/Core.hs: 491,68 ghc cant infer that the last part is a String (I guess due to OverloadedStrings)

<b></b>

    isOk c = isAlphaChar c || isDigitChar c || c `elem` (":@$-_.~" :: String)
- harp:  in Match.hs: the type Match is made a Monad Instance but not Functor/Applicative, which violates the [Functor-Applicative-Monad-Proposal](https://wiki.haskell.org/Functor-Applicative-Monad_Proposal).

<b></b>

    bindM (Match f) k = Match (\es -> let aes = f es in concatMap help aes)
        where help (a, es) = let Match g = k a in g es
    instance Functor (Match e) where
      fmap f mx = bindM mx (\x -> return $ f x)

    instance Applicative (Match e) where
      pure x = Match (\es -> [(x, es)])
      mf <*> mx = bindM mf (\f -> bindM mx (\x -> return $ f x))

    instance Monad (Match e) where
      return = pure
      (>>=) = bindM

Sorry if this is bad Style.
I'm not sure if the harp-part belongs here, but I couldnt find any better place to post this.
After these fixes everything compiled, but the example-dot-org webserver gave me a redirect loop in the browser.
Greets
Tobias Simetsreiter

**Comment by stepcut** [comment]
Ugh. I uploaded a new `web-plugins`. Sadly it was patched on my system, and in github, but I forgot to upload it to hackage. This is why I am working to get more integration testing. I currently test that github builds, but I need to add some rules that check that hackage builds.

The harp issue is known, I just need to get Niklas to give me upload rights to harp on hackage.

The redirect loop could be due to a bug that was just fixed last night. Namely this patch,

https://github.com/clckwrks/clckwrks/commit/ba6fddc10a127d7c130f023f553e57ca80b39a21

clckwrks now attempts to make sure all requests are redirected to a canonical name so that things like angularjs do not complain about different domains (www.example.org vs example.org) or different schemes (http vs https).

Also, make sure you have markdown installed (or, as of last night, pandoc). If you do not then you will get a blank page. Clearly the code which calls pandoc should provide better error reporting.

**Comment by dasimmet** [comment]
okay, rebuilding clckwrks from git worked.
thanks
