### ISSUE TITLE
Build failure: missing hsx2hs

### ISSUE THREAD

**Issue by snoyberg** [clckwrks/clckwrks#4]
Since the 0.23.19 release, Stackage has been unable to build clckwrks due to this missing build tool. I think the solution is to add that package to Stackage. Are you OK with it being under your maintainership? In the meanwhile, I'll put an upper bound in place.

**Comment by stepcut** [comment]
The build failed because I had temporarily switched from 'Custom' build type to 'Simple' build type. I did not really mean to commit that change as part of updating to the latest aeson (and have already revert in github). I was hoping to edit the metadata on hackage, but apparently I am not allowed to edit build-type. I have now uploaded a new version, 0.23.19.1.

I guess I am already the unofficial maintainer of hsx2hs, so adding it to stackage is fine.
